import { v4 as uuidv4 } from "uuid";
import { PhoneInfo } from "../../types";

const phones: PhoneInfo[] = [
  {
    id: 1,
    name: "Смартфон Apple iPhone 11 128 Gb Slim Box черный",
    imgUrl: [
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
    ],
    price: 7300000,
    fromPrice: 2445000,
    times: 24,
    present: true,
    change: true,
    discount: true,
  },
  {
    id: 2,
    name: "Смартфон Apple iPhone 11 128 Gb Slim Box черный",
    imgUrl: [
      "/images/phone2.png",
      "/images/phone2.png",
      "/images/phone2.png",
      "/images/phone2.png",
      "/images/phone2.png",
    ],
    price: 7300000,
    fromPrice: 2445000,
    times: 24,
    present: true,
    change: true,
    discount: true,
  },
  {
    id: 3,
    name: "Наушники Apple Airpo Slim Box черный",
    imgUrl: [
      "/images/ear.png",
      "/images/ear.png",
      "/images/ear.png",
      "/images/ear.png",
      "/images/ear.png",
    ],
    price: 7300000,
    fromPrice: 2445000,
    times: 24,
    present: true,
    change: true,
    discount: true,
  },
  {
    id: 4,
    name: "Смартфон Apple iPhone 11 128 Gb Slim Box черный",
    imgUrl: [
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
    ],
    price: 7300000,
    fromPrice: 2445000,
    times: 24,
    present: true,
    change: true,
    discount: true,
  },
  {
    id: 5,
    name: "Смартфон Apple iPhone 11 128 Gb Slim Box черный",
    imgUrl: [
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
    ],
    price: 7300000,
    fromPrice: 2445000,
    times: 24,
    present: true,
    change: true,
    discount: true,
  },
  {
    id: 6,
    name: "Смартфон Apple iPhone 11 128 Gb Slim Box черный",
    imgUrl: [
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
    ],
    price: 7300000,
    fromPrice: 2445000,
    times: 24,
    present: true,
    change: true,
    discount: true,
  },
  {
    id: 7,
    name: "Смартфон Apple iPhone 11 128 Gb Slim Box черный",
    imgUrl: [
      "/images/phone3.png",
      "/images/phone3.png",
      "/images/phone3.png",
      "/images/phone3.png",
      "/images/phone3.png",
    ],
    price: 7300000,
    fromPrice: 2445000,
    times: 24,
    present: true,
    change: true,
    discount: true,
  },
  {
    id: 8,
    name: "Смартфон Apple iPhone 11 128 Gb Slim Box черный",
    imgUrl: [
      "/images/phone2.png",
      "/images/phone2.png",
      "/images/phone2.png",
      "/images/phone2.png",
      "/images/phone2.png",
    ],
    price: 7300000,
    fromPrice: 2445000,
    times: 24,
    present: false,
    change: false,
    discount: false,
  },
  {
    id: 9,
    name: "Смартфон Apple iPhone 11 128 Gb Slim Box черный",
    imgUrl: [
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
    ],
    price: 7300000,
    fromPrice: 2445000,
    times: 24,
    present: true,
    change: true,
    discount: true,
  },
  {
    id: 10,
    name: "Наушники Apple Airpo Slim Box черный",
    imgUrl: [
      "/images/ear.png",
      "/images/ear.png",
      "/images/ear.png",
      "/images/ear.png",
      "/images/ear.png",
    ],
    price: 7300000,
    fromPrice: 2445000,
    times: 24,
    present: true,
    change: true,
    discount: false,
  },
  {
    id: 11,
    name: "Смартфон Apple iPhone 11 128 Gb Slim Box черный",
    imgUrl: [
      "/images/phone3.png",
      "/images/phone3.png",
      "/images/phone3.png",
      "/images/phone3.png",
      "/images/phone3.png",
    ],
    price: 7300000,
    fromPrice: 2445000,
    times: 24,
    present: true,
    change: true,
    discount: true,
  },
  {
    id: 12,
    name: "Смартфон Apple iPhone 11 128 Gb Slim Box черный",
    imgUrl: [
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
    ],
    price: 7300000,
    fromPrice: 2445000,
    times: 24,
    present: false,
    change: true,
    discount: false,
  },
  {
    id: 13,
    name: "Смартфон Apple iPhone 11 128 Gb Slim Box черный",
    imgUrl: [
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
    ],
    price: 7300000,
    fromPrice: 2445000,
    times: 24,
    present: true,
    change: true,
    discount: true,
  },
  {
    id: 14,
    name: "Смартфон Apple iPhone 11 128 Gb Slim Box черный",
    imgUrl: [
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
    ],
    price: 234243,
    fromPrice: 23443432,
    times: 24,
    present: true,
    change: true,
    discount: true,
  },
  {
    id: 15,
    name: "Смартфон Apple iPhone 11 128 Gb Slim Box черный",
    imgUrl: [
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
    ],
    price: 244234432,
    fromPrice: 2445000,
    times: 24,
    present: true,
    change: true,
    discount: true,
  },
  {
    id: 16,
    name: "Смартфон Apple iPhone 11 128 Gb Slim Box черный",
    imgUrl: [
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
    ],
    price: 4534534,
    fromPrice: 2445000,
    times: 24,
    present: true,
    change: true,
    discount: true,
  },
  {
    id: 17,
    name: "Смартфон Apple iPhone 11 128 Gb Slim Box черный",
    imgUrl: [
      "/images/phone2.png",
      "/images/phone2.png",
      "/images/phone2.png",
      "/images/phone2.png",
      "/images/phone2.png",
    ],
    price: 7300000,
    fromPrice: 2445000,
    times: 24,
    present: false,
    change: false,
    discount: true,
  },
  {
    id: 18,
    name: "Смартфон Apple iPhone 11 128 Gb Slim Box черный",
    imgUrl: [
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
    ],
    price: 7300000,
    fromPrice: 2445000,
    times: 24,
    present: true,
    change: true,
    discount: true,
  },
  {
    id: 19,
    name: "Смартфон Apple iPhone 11 128 Gb Slim Box черный",
    imgUrl: [
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
    ],
    price: 7300000,
    fromPrice: 2445000,
    times: 24,
    present: true,
    change: false,
    discount: true,
  },
  {
    id: 20,
    name: "Смартфон Apple iPhone 11 128 Gb Slim Box черный",
    imgUrl: [
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
      "/images/phone1.png",
    ],
    price: 7300000,
    fromPrice: 2445000,
    times: 24,
    present: false,
    change: true,
    discount: true,
  },
];

export default phones;
